---
title: "First Knit"
author: "Andres Castellanos"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attended Valley Academy of Arts and Science, down in the San Fernando Valley, I graduated in 2021. Mty graduation was a bit strange since it was during COVID. To me personally I think English is easier because once I get in a flow I can just keep writing. Math was a bit more dificult for me, I would often doze off during cruitial steps and wouldn't ask questions.My goal as an adult is to actually understand the material and ask questions if I need help. I did best in history, I enjoy learning about past historical events. I also found it fun researching important historical figures.
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
   I use an Apple Macbook, which is a laptop. On a scale of 1-10 I would say I am about a 7, but as we go further into setting up this program on posit, I would say a lower number such as 5 or 4. This stuff feels like rocket science to me but I am getting better everyday and used to it. I have pretty good internet access at my house, we do have quite a bit of -WIFI devices, but I don't think it should affect anything. 

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   
 I don't really have a prefrence, I know my name can be a bit difficult to say. A nickname I have is Andy, if it's easier it's okay for anyone to call me that. My mom actually named me Andres for the intention for people to call me Andy. Not until like 2020 did people start calling me Andy. 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   
 My achievements in life would be to solidified in a career and to be able to support my future family comfortably. I want to be happy with what I do and have a nice work- life balance. The college subvject I think would be a great interest to me would probably be History of some kind. Like I mentioned earlier I like learning about historical figures and times. For right now I want to have my bachelors and move up from there.




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  Yes, I have been to a few foreign countries. I have been to different parts of Mexico, Puerto Rico, Dominican Republic, and Saint Martinn. I want to visit more countries, I love to travel., Next up would probably be somewhere like Jamacia. I have not been in the military. If I would have to choose I would probably be in the Marines because I have family in that branch.   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   I believe I have taken Math 115 in the past but I don't think I did so well. I did not know that. I want to maintain above a B average. Right now I am unsure about my plans, I just want to finish my generals.
 






  




